### ISSUE TITLE
Cant drop percentage even though its almost 100% visually the same.

### ISSUE THREAD

**Issue by char1129** [char1129/accessibility-fixer-upper#1]
Also having issues with the aria-label/details.
At 96% with 2 failed tests.

Please help. I'm about to throw my laptop against the wall. 😊

@muxlowc

![171](https://user-images.githubusercontent.com/55107755/76815237-752f0e80-67d3-11ea-8c6f-2f26c99e43b0.jpg)

**Comment by muxlowc** [comment]
@char1129 looking right now- please don't harm your laptop!

**Comment by muxlowc** [comment]
@char1129 Okay, so I think what might be happening is that you have your MAIN in between your sections. What it should look like is:

` <main>
       <section>...
       <section>...
       <section>...
    </main>
    <footer>
    </footer>`

This should fix all of those aria issues (remove that one aria-details you seem to have added to test it)

It seems like the text is being weird, but I can't seem to figure out why - if you get everything else to pass but the screenshots, let me know, and I'll just give you the mark (but I'll also message Thomas to see if there's a reason/fix)

**Comment by char1129** [comment]
Thank you! @muxlowc  I'll give it a try and let you know once I get it working before I close the issue 👍

**Comment by char1129** [comment]
And I accidentally close it. Alrighty~! I'll let you know how it goes!

**Comment by char1129** [comment]
@muxlowc I've moved the sections within the main and am still getting aria-details. I managed to get the  screenshots within the percentage for passing. I now have a new error about an id the main is looking for... but already has.

**SO** frustrating. 

![Screen Shot 2020-03-21 at 12 47 35 AM](https://user-images.githubusercontent.com/55107755/77219590-bc880880-6b0d-11ea-8ab4-69ab425ee0f2.png)

**Comment by muxlowc** [comment]
@char1129 i think i solved your aria-details issue!

Move your end DIV tag that you had closing after your H2/P and move it to end at the bottom of your products instead.

```
<section role="complementary" id="shrubs" tabindex="0">
      <div class="wrapper gutter-1-2">
        <h2 class="push-0 color-brand-dark">Products</h2>
        <p class="mega max-length not-centered">If you do not tell us where we can buy a shrubbery, my friend and I will say… we will say… “nee”.</p>

      <ul...
......
<div class="gutter-1-4 push" id="two-level-shrub">
            <h3 class="mega push-0">Two-level shrubbery</h3>
            <p>Two level shrubbery is where I put two shrubs at different heights, usually with a little path running down the middle.</p>
          </div>
        </li>
      </ul>
    </div>
```

I think you might to play around again with padding, and let me know if you can't pass because of weird text-sizing issues with the screenshots

**Comment by char1129** [comment]
@muxlowc  THANK YOU! let me give this a try!

**Comment by char1129** [comment]
AHH it fixed everything!! Thank you! @muxlowc
